spring.application.name=demo
spring.datasource.url=jdbc:mysql://localhost:3306/BillItemManagerment
spring.datasource.username=root
spring.datasource.password=swaroop@db
spring.jpa.hibernate.ddl-auto=update