spring.application.name=MysqlConnection

spring.datasource.url=jdbc:mysql://localhost:3306/mtd_project
spring.datasource.username=root
spring.datasource.password=swaroop@db
spring.jpa.hibernate.ddl-auto=update