spring.application.name=BillsManagement

spring.datasource.url=jdbc:mysql://localhost:3306/bill_managerment
spring.datasource.username=root
spring.datasource.password=swaroop@db
spring.jpa.hibernate.ddl-auto=update
