spring.appllicationname=Application

spring.datasource.url=jdbc:mysql://localhost:3306/addition_example
spring.datasource.username=root
spring.datasource.password=swaroop@db
spring.jpa.hibernate.ddl-auto=update